-- ===================================================
-- PeoplePay360 PostgreSQL Database Schema (16 Tables)
-- Compatible with Supabase PostgreSQL (auth.users + public schema)
-- ===================================================

-- Drop existing public tables in reverse dependency order if any exist
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.payslip_lines CASCADE;
DROP TABLE IF EXISTS public.payslips CASCADE;
DROP TABLE IF EXISTS public.payruns CASCADE;
DROP TABLE IF EXISTS public.salary_rules CASCADE;
DROP TABLE IF EXISTS public.salary_structures CASCADE;
DROP TABLE IF EXISTS public.leave_requests CASCADE;
DROP TABLE IF EXISTS public.leave_allocations CASCADE;
DROP TABLE IF EXISTS public.leave_types CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.contracts CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.working_schedules CASCADE;
DROP TABLE IF EXISTS public.departments CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

-- ---------------------------------------------------
-- 01. roles
-- ---------------------------------------------------
CREATE TABLE public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL UNIQUE,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT roles_code_check
        CHECK (code IN (
            'ADMIN',
            'HR_MANAGER',
            'HR_PAYROLL_USER',
            'HR_PAYROLL_MANAGER',
            'EMPLOYEE'
        ))
);

-- Seed predefined roles
INSERT INTO public.roles (code, name, description)
VALUES
('ADMIN', 'Administrator', 'Full platform administration'),
('HR_MANAGER', 'HR Manager', 'HR master data and leave management'),
('HR_PAYROLL_USER', 'HR Payroll User', 'HR plus payroll operational access'),
('HR_PAYROLL_MANAGER', 'HR Payroll Manager', 'Full HR and payroll management'),
('EMPLOYEE', 'Employee', 'Own employee, attendance and leave access')
ON CONFLICT (code) DO NOTHING;

-- ---------------------------------------------------
-- 02. departments
-- ---------------------------------------------------
CREATE TABLE public.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    code text UNIQUE,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------
-- 03. working_schedules
-- ---------------------------------------------------
CREATE TABLE public.working_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    code text UNIQUE,
    monday_start time,
    monday_end time,
    tuesday_start time,
    tuesday_end time,
    wednesday_start time,
    wednesday_end time,
    thursday_start time,
    thursday_end time,
    friday_start time,
    friday_end time,
    saturday_start time,
    saturday_end time,
    sunday_start time,
    sunday_end time,
    break_minutes integer NOT NULL DEFAULT 60,
    weekly_hours numeric(6,2) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT schedule_break_check
        CHECK (break_minutes >= 0)
);

-- ---------------------------------------------------
-- 04. employees
-- Central table of the application
-- ---------------------------------------------------
CREATE TABLE public.employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code text NOT NULL UNIQUE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL UNIQUE,
    phone text,
    date_of_birth date,
    joining_date date NOT NULL,
    termination_date date,
    department_id bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    manager_id bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    schedule_id bigint REFERENCES public.working_schedules(id) ON DELETE SET NULL,
    designation text,
    employee_type text NOT NULL DEFAULT 'FULL_TIME',
    status text NOT NULL DEFAULT 'ACTIVE',
    pipeline_stage text NOT NULL DEFAULT 'NEW_JOINER',
    address text,
    city text,
    state text,
    country text DEFAULT 'India',
    postal_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT employees_type_check
        CHECK (employee_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT employees_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'TERMINATED')),
    CONSTRAINT employees_dates_check
        CHECK (termination_date IS NULL OR termination_date >= joining_date)
);

-- ---------------------------------------------------
-- 05. users
-- Application user accounts referencing Supabase auth.users
-- ---------------------------------------------------
CREATE TABLE public.users (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role_id bigint NOT NULL REFERENCES public.roles(id),
    employee_id bigint UNIQUE REFERENCES public.employees(id) ON DELETE SET NULL,
    email text NOT NULL UNIQUE,
    full_name text,
    is_active boolean NOT NULL DEFAULT true,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------
-- 06. salary_structures
-- ---------------------------------------------------
CREATE TABLE public.salary_structures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL UNIQUE,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------
-- 07. contracts
-- ---------------------------------------------------
CREATE TABLE public.contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    contract_number text NOT NULL UNIQUE,
    start_date date NOT NULL,
    end_date date,
    employment_type text NOT NULL,
    wage numeric(14,2) NOT NULL,
    currency varchar(3) NOT NULL DEFAULT 'INR',
    pay_frequency text NOT NULL DEFAULT 'MONTHLY',
    salary_structure_id bigint REFERENCES public.salary_structures(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT contracts_wage_check
        CHECK (wage >= 0),
    CONSTRAINT contracts_dates_check
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT contracts_status_check
        CHECK (status IN ('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED'))
);

-- ---------------------------------------------------
-- 08. attendance
-- ---------------------------------------------------
CREATE TABLE public.attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    attendance_date date NOT NULL,
    check_in timestamptz,
    check_out timestamptz,
    worked_hours numeric(6,2) NOT NULL DEFAULT 0,
    overtime_hours numeric(6,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'PRESENT',
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT attendance_unique_day
        UNIQUE (employee_id, attendance_date),
    CONSTRAINT attendance_hours_check
        CHECK (worked_hours >= 0 AND overtime_hours >= 0)
);

-- ---------------------------------------------------
-- 09. leave_types
-- ---------------------------------------------------
CREATE TABLE public.leave_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL UNIQUE,
    unit text NOT NULL DEFAULT 'DAYS',
    requires_allocation boolean NOT NULL DEFAULT true,
    is_paid boolean NOT NULL DEFAULT true,
    affects_payroll boolean NOT NULL DEFAULT false,
    requires_approval boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT leave_unit_check
        CHECK (unit IN ('DAYS', 'HOURS'))
);

-- ---------------------------------------------------
-- 10. leave_allocations
-- ---------------------------------------------------
CREATE TABLE public.leave_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    leave_type_id bigint NOT NULL REFERENCES public.leave_types(id),
    start_date date NOT NULL,
    end_date date NOT NULL,
    total_days numeric(8,2) NOT NULL DEFAULT 0,
    used_days numeric(8,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'APPROVED',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT allocation_dates_check
        CHECK (end_date >= start_date),
    CONSTRAINT allocation_values_check
        CHECK (total_days >= 0 AND used_days >= 0 AND used_days <= total_days),
    CONSTRAINT allocation_status_check
        CHECK (status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED'))
);

-- ---------------------------------------------------
-- 11. leave_requests
-- ---------------------------------------------------
CREATE TABLE public.leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    leave_type_id bigint NOT NULL REFERENCES public.leave_types(id),
    start_date date NOT NULL,
    end_date date NOT NULL,
    days numeric(8,2) NOT NULL,
    reason text,
    status text NOT NULL DEFAULT 'PENDING',
    approved_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
    approved_at timestamptz,
    rejection_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT leave_dates_check
        CHECK (end_date >= start_date),
    CONSTRAINT leave_days_check
        CHECK (days > 0),
    CONSTRAINT leave_request_status_check
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

-- ---------------------------------------------------
-- 12. salary_rules
-- ---------------------------------------------------
CREATE TABLE public.salary_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salary_structure_id bigint NOT NULL REFERENCES public.salary_structures(id) ON DELETE CASCADE,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    category text NOT NULL,
    sequence integer NOT NULL,
    calculation_type text NOT NULL,
    fixed_amount numeric(14,2),
    percentage numeric(8,4),
    formula text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT salary_rule_category_check
        CHECK (category IN ('BASIC', 'ALLOWANCE', 'GROSS', 'DEDUCTION', 'CONTRIBUTION', 'NET')),
    CONSTRAINT salary_rule_calculation_check
        CHECK (calculation_type IN ('FIXED', 'PERCENTAGE', 'FORMULA')),
    CONSTRAINT salary_rule_value_check
        CHECK (calculation_type <> 'FIXED' OR fixed_amount IS NOT NULL),
    CONSTRAINT salary_rule_percentage_check
        CHECK (calculation_type <> 'PERCENTAGE' OR percentage IS NOT NULL)
);

-- ---------------------------------------------------
-- 13. payruns
-- ---------------------------------------------------
CREATE TABLE public.payruns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_number text NOT NULL UNIQUE,
    salary_structure_id bigint NOT NULL REFERENCES public.salary_structures(id),
    period_start date NOT NULL,
    period_end date NOT NULL,
    status text NOT NULL DEFAULT 'DRAFT',
    employee_count integer NOT NULL DEFAULT 0,
    total_gross numeric(16,2) NOT NULL DEFAULT 0,
    total_deductions numeric(16,2) NOT NULL DEFAULT 0,
    total_net numeric(16,2) NOT NULL DEFAULT 0,
    created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
    computed_at timestamptz,
    validated_at timestamptz,
    paid_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT payrun_dates_check
        CHECK (period_end >= period_start),
    CONSTRAINT payrun_status_check
        CHECK (status IN ('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', 'CANCELLED'))
);

-- ---------------------------------------------------
-- 14. payslips
-- ---------------------------------------------------
CREATE TABLE public.payslips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_number text NOT NULL UNIQUE,
    payrun_id bigint NOT NULL REFERENCES public.payruns(id) ON DELETE CASCADE,
    employee_id bigint NOT NULL REFERENCES public.employees(id),
    contract_id bigint NOT NULL REFERENCES public.contracts(id),
    salary_structure_id bigint NOT NULL REFERENCES public.salary_structures(id),
    period_start date NOT NULL,
    period_end date NOT NULL,
    worked_days numeric(8,2) NOT NULL DEFAULT 0,
    paid_days numeric(8,2) NOT NULL DEFAULT 0,
    gross_amount numeric(14,2) NOT NULL DEFAULT 0,
    deduction_amount numeric(14,2) NOT NULL DEFAULT 0,
    net_amount numeric(14,2) NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'DRAFT',
    payment_status text NOT NULL DEFAULT 'UNPAID',
    pdf_url text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT payslip_dates_check
        CHECK (period_end >= period_start),
    CONSTRAINT payslip_amount_check
        CHECK (gross_amount >= 0 AND deduction_amount >= 0 AND net_amount >= 0),
    CONSTRAINT payslip_status_check
        CHECK (status IN ('DRAFT', 'COMPUTED', 'VALIDATED', 'PAID', 'CANCELLED')),
    CONSTRAINT payslip_payment_status_check
        CHECK (payment_status IN ('UNPAID', 'PAID', 'FAILED')),
    UNIQUE (payrun_id, employee_id)
);

-- ---------------------------------------------------
-- 15. payslip_lines
-- ---------------------------------------------------
CREATE TABLE public.payslip_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id bigint NOT NULL REFERENCES public.payslips(id) ON DELETE CASCADE,
    rule_id bigint REFERENCES public.salary_rules(id) ON DELETE SET NULL,
    rule_code text NOT NULL,
    rule_name text NOT NULL,
    category text NOT NULL,
    sequence integer NOT NULL,
    quantity numeric(12,4) NOT NULL DEFAULT 1,
    rate numeric(12,4) NOT NULL DEFAULT 100,
    amount numeric(14,2) NOT NULL DEFAULT 0,
    calculation_details jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------
-- 16. audit_logs
-- ---------------------------------------------------
CREATE TABLE public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id bigint,
    old_data jsonb,
    new_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------
-- Performance Indexes
-- ---------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_employees_department ON public.employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_manager ON public.employees(manager_id);
CREATE INDEX IF NOT EXISTS idx_contracts_employee ON public.contracts(employee_id);
CREATE INDEX IF NOT EXISTS idx_contracts_dates ON public.contracts(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_date ON public.attendance(employee_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_leave_requests_employee ON public.leave_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_allocations_employee ON public.leave_allocations(employee_id);
CREATE INDEX IF NOT EXISTS idx_salary_rules_structure ON public.salary_rules(salary_structure_id);
CREATE INDEX IF NOT EXISTS idx_payruns_period ON public.payruns(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_payslips_employee ON public.payslips(employee_id);
CREATE INDEX IF NOT EXISTS idx_payslips_payrun ON public.payslips(payrun_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.audit_logs(entity_type, entity_id);
